# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

module Client

using Dates, TimeZones
using OpenAPI
using OpenAPI.Clients

const API_VERSION = "0.28.0"

include("modelincludes.jl")

include("apis/api_DataAPIApi.jl")
include("apis/api_HealthAPIApi.jl")

end # module Client
