name = "OpenPolicyAgent"
uuid = "8f257efb-743c-4ebc-8197-d291a1f743b4"
authors = ["Tanmay Mohapatra <tanmaykm@gmail.com>"]
version = "0.1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
OpenAPI = "d5e62ea6-ddf3-4d43-8e4c-ad5e6c8bfd7d"
OpenPolicyAgent_jll = "6ea5c882-2ec3-5826-84d1-aff636352c13"
TimeZones = "f269a46b-ccf7-5d73-abea-4c690281aa53"

[compat]
OpenAPI = "0.1"
TimeZones = "1"
julia = "1"
OpenPolicyAgent_jll = "0.55"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
