# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""policy_ast_rules_inner_body_inner_terms_inner

    PolicyAstRulesInnerBodyInnerTermsInner(;
        type=nothing,
        value=nothing,
    )

    - type::String : The type of the term variable
    - value::Vector{PolicyAstRulesInnerBodyInnerTermsInnerValueInner} : The list of types and values for the term variable
"""
Base.@kwdef mutable struct PolicyAstRulesInnerBodyInnerTermsInner <: OpenAPI.APIModel
    type::Union{Nothing, String} = nothing
    value::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{PolicyAstRulesInnerBodyInnerTermsInnerValueInner} }

    function PolicyAstRulesInnerBodyInnerTermsInner(type, value, )
        OpenAPI.validate_property(PolicyAstRulesInnerBodyInnerTermsInner, Symbol("type"), type)
        OpenAPI.validate_property(PolicyAstRulesInnerBodyInnerTermsInner, Symbol("value"), value)
        return new(type, value, )
    end
end # type PolicyAstRulesInnerBodyInnerTermsInner

const _property_types_PolicyAstRulesInnerBodyInnerTermsInner = Dict{Symbol,String}(Symbol("type")=>"String", Symbol("value")=>"Vector{PolicyAstRulesInnerBodyInnerTermsInnerValueInner}", )
OpenAPI.property_type(::Type{ PolicyAstRulesInnerBodyInnerTermsInner }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_PolicyAstRulesInnerBodyInnerTermsInner[name]))}

function check_required(o::PolicyAstRulesInnerBodyInnerTermsInner)
    true
end

function OpenAPI.validate_property(::Type{ PolicyAstRulesInnerBodyInnerTermsInner }, name::Symbol, val)
end
