# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""response200Metrics_metrics

    Response200MetricsMetrics(;
        timer_rego_input_parse_ns=nothing,
        timer_rego_query_parse_ns=nothing,
        timer_rego_query_compile_ns=nothing,
        timer_rego_query_eval_ns=nothing,
        timer_rego_module_parse_ns=nothing,
        timer_rego_module_compile_ns=nothing,
        timer_server_handler_ns=nothing,
        timer_server_read_bytes_ns=nothing,
        counter_server_query_cache_hit=nothing,
        timer_query_compile_stage_build_comprehension_index_ns=nothing,
        timer_query_compile_stage_check_safety_ns=nothing,
        timer_query_compile_stage_check_types_ns=nothing,
        timer_query_compile_stage_check_undefined_funcs_ns=nothing,
        timer_query_compile_stage_check_unsafe_builtins_ns=nothing,
        timer_query_compile_stage_resolve_refs_ns=nothing,
        timer_query_compile_stage_rewrite_comprehension_terms_ns=nothing,
        timer_query_compile_stage_rewrite_dynamic_terms_ns=nothing,
        timer_query_compile_stage_rewrite_expr_terms_ns=nothing,
        timer_query_compile_stage_rewrite_local_vars_ns=nothing,
        timer_query_compile_stage_rewrite_to_capture_value_ns=nothing,
        timer_query_compile_stage_rewrite_with_values_ns=nothing,
    )

    - timer_rego_input_parse_ns::Float64 : Time taken (in nanonseconds) to parse the input
    - timer_rego_query_parse_ns::Float64 : Time taken (in nanoseconds) to parse the query
    - timer_rego_query_compile_ns::Float64 : Time taken (in nanoseconds) to compile the query
    - timer_rego_query_eval_ns::Float64 : Time taken (in nanonseconds) to evaluate the query
    - timer_rego_module_parse_ns::Float64 : Time taken (in nanoseconds) to parse the input policy module
    - timer_rego_module_compile_ns::Float64 : Time taken (in nanonseconds) to compile the loaded policy modules
    - timer_server_handler_ns::Float64 : Time taken (in nanoseconds) to handle the API request
    - timer_server_read_bytes_ns::Float64 : *Description is forthcoming*
    - counter_server_query_cache_hit::Float64 : *Description is forthcoming*
    - timer_query_compile_stage_build_comprehension_index_ns::Float64 : (Only returned if &#x60;instrument&#x60; is true.) *Description is forthcoming*
    - timer_query_compile_stage_check_safety_ns::Float64 : (Only returned if &#x60;instrument&#x60; is true.) *Description is forthcoming*
    - timer_query_compile_stage_check_types_ns::Float64 : (Only returned if &#x60;instrument&#x60; is true.) *Description is forthcoming*
    - timer_query_compile_stage_check_undefined_funcs_ns::Float64 : (Only returned if &#x60;instrument&#x60; is true.) *Description is forthcoming*
    - timer_query_compile_stage_check_unsafe_builtins_ns::Float64 : (Only returned if &#x60;instrument&#x60; is true.) *Description is forthcoming*
    - timer_query_compile_stage_resolve_refs_ns::Float64 : (Only returned if &#x60;instrument&#x60; is true.) *Description is forthcoming*
    - timer_query_compile_stage_rewrite_comprehension_terms_ns::Float64 : (Only returned if &#x60;instrument&#x60; is true.) *Description is forthcoming*
    - timer_query_compile_stage_rewrite_dynamic_terms_ns::Float64 : (Only returned if &#x60;instrument&#x60; is true.) *Description is forthcoming*
    - timer_query_compile_stage_rewrite_expr_terms_ns::Float64 : (Only returned if &#x60;instrument&#x60; is true.) *Description is forthcoming*
    - timer_query_compile_stage_rewrite_local_vars_ns::Float64 : (Only returned if &#x60;instrument&#x60; is true.) *Description is forthcoming*
    - timer_query_compile_stage_rewrite_to_capture_value_ns::Float64 : (Only returned if &#x60;instrument&#x60; is true.) *Description is forthcoming*
    - timer_query_compile_stage_rewrite_with_values_ns::Float64 : (Only returned if &#x60;instrument&#x60; is true.) *Description is forthcoming*
"""
Base.@kwdef mutable struct Response200MetricsMetrics <: OpenAPI.APIModel
    timer_rego_input_parse_ns::Union{Nothing, Float64} = nothing
    timer_rego_query_parse_ns::Union{Nothing, Float64} = nothing
    timer_rego_query_compile_ns::Union{Nothing, Float64} = nothing
    timer_rego_query_eval_ns::Union{Nothing, Float64} = nothing
    timer_rego_module_parse_ns::Union{Nothing, Float64} = nothing
    timer_rego_module_compile_ns::Union{Nothing, Float64} = nothing
    timer_server_handler_ns::Union{Nothing, Float64} = nothing
    timer_server_read_bytes_ns::Union{Nothing, Float64} = nothing
    counter_server_query_cache_hit::Union{Nothing, Float64} = nothing
    timer_query_compile_stage_build_comprehension_index_ns::Union{Nothing, Float64} = nothing
    timer_query_compile_stage_check_safety_ns::Union{Nothing, Float64} = nothing
    timer_query_compile_stage_check_types_ns::Union{Nothing, Float64} = nothing
    timer_query_compile_stage_check_undefined_funcs_ns::Union{Nothing, Float64} = nothing
    timer_query_compile_stage_check_unsafe_builtins_ns::Union{Nothing, Float64} = nothing
    timer_query_compile_stage_resolve_refs_ns::Union{Nothing, Float64} = nothing
    timer_query_compile_stage_rewrite_comprehension_terms_ns::Union{Nothing, Float64} = nothing
    timer_query_compile_stage_rewrite_dynamic_terms_ns::Union{Nothing, Float64} = nothing
    timer_query_compile_stage_rewrite_expr_terms_ns::Union{Nothing, Float64} = nothing
    timer_query_compile_stage_rewrite_local_vars_ns::Union{Nothing, Float64} = nothing
    timer_query_compile_stage_rewrite_to_capture_value_ns::Union{Nothing, Float64} = nothing
    timer_query_compile_stage_rewrite_with_values_ns::Union{Nothing, Float64} = nothing

    function Response200MetricsMetrics(timer_rego_input_parse_ns, timer_rego_query_parse_ns, timer_rego_query_compile_ns, timer_rego_query_eval_ns, timer_rego_module_parse_ns, timer_rego_module_compile_ns, timer_server_handler_ns, timer_server_read_bytes_ns, counter_server_query_cache_hit, timer_query_compile_stage_build_comprehension_index_ns, timer_query_compile_stage_check_safety_ns, timer_query_compile_stage_check_types_ns, timer_query_compile_stage_check_undefined_funcs_ns, timer_query_compile_stage_check_unsafe_builtins_ns, timer_query_compile_stage_resolve_refs_ns, timer_query_compile_stage_rewrite_comprehension_terms_ns, timer_query_compile_stage_rewrite_dynamic_terms_ns, timer_query_compile_stage_rewrite_expr_terms_ns, timer_query_compile_stage_rewrite_local_vars_ns, timer_query_compile_stage_rewrite_to_capture_value_ns, timer_query_compile_stage_rewrite_with_values_ns, )
        OpenAPI.validate_property(Response200MetricsMetrics, Symbol("timer_rego_input_parse_ns"), timer_rego_input_parse_ns)
        OpenAPI.validate_property(Response200MetricsMetrics, Symbol("timer_rego_query_parse_ns"), timer_rego_query_parse_ns)
        OpenAPI.validate_property(Response200MetricsMetrics, Symbol("timer_rego_query_compile_ns"), timer_rego_query_compile_ns)
        OpenAPI.validate_property(Response200MetricsMetrics, Symbol("timer_rego_query_eval_ns"), timer_rego_query_eval_ns)
        OpenAPI.validate_property(Response200MetricsMetrics, Symbol("timer_rego_module_parse_ns"), timer_rego_module_parse_ns)
        OpenAPI.validate_property(Response200MetricsMetrics, Symbol("timer_rego_module_compile_ns"), timer_rego_module_compile_ns)
        OpenAPI.validate_property(Response200MetricsMetrics, Symbol("timer_server_handler_ns"), timer_server_handler_ns)
        OpenAPI.validate_property(Response200MetricsMetrics, Symbol("timer_server_read_bytes_ns"), timer_server_read_bytes_ns)
        OpenAPI.validate_property(Response200MetricsMetrics, Symbol("counter_server_query_cache_hit"), counter_server_query_cache_hit)
        OpenAPI.validate_property(Response200MetricsMetrics, Symbol("timer_query_compile_stage_build_comprehension_index_ns"), timer_query_compile_stage_build_comprehension_index_ns)
        OpenAPI.validate_property(Response200MetricsMetrics, Symbol("timer_query_compile_stage_check_safety_ns"), timer_query_compile_stage_check_safety_ns)
        OpenAPI.validate_property(Response200MetricsMetrics, Symbol("timer_query_compile_stage_check_types_ns"), timer_query_compile_stage_check_types_ns)
        OpenAPI.validate_property(Response200MetricsMetrics, Symbol("timer_query_compile_stage_check_undefined_funcs_ns"), timer_query_compile_stage_check_undefined_funcs_ns)
        OpenAPI.validate_property(Response200MetricsMetrics, Symbol("timer_query_compile_stage_check_unsafe_builtins_ns"), timer_query_compile_stage_check_unsafe_builtins_ns)
        OpenAPI.validate_property(Response200MetricsMetrics, Symbol("timer_query_compile_stage_resolve_refs_ns"), timer_query_compile_stage_resolve_refs_ns)
        OpenAPI.validate_property(Response200MetricsMetrics, Symbol("timer_query_compile_stage_rewrite_comprehension_terms_ns"), timer_query_compile_stage_rewrite_comprehension_terms_ns)
        OpenAPI.validate_property(Response200MetricsMetrics, Symbol("timer_query_compile_stage_rewrite_dynamic_terms_ns"), timer_query_compile_stage_rewrite_dynamic_terms_ns)
        OpenAPI.validate_property(Response200MetricsMetrics, Symbol("timer_query_compile_stage_rewrite_expr_terms_ns"), timer_query_compile_stage_rewrite_expr_terms_ns)
        OpenAPI.validate_property(Response200MetricsMetrics, Symbol("timer_query_compile_stage_rewrite_local_vars_ns"), timer_query_compile_stage_rewrite_local_vars_ns)
        OpenAPI.validate_property(Response200MetricsMetrics, Symbol("timer_query_compile_stage_rewrite_to_capture_value_ns"), timer_query_compile_stage_rewrite_to_capture_value_ns)
        OpenAPI.validate_property(Response200MetricsMetrics, Symbol("timer_query_compile_stage_rewrite_with_values_ns"), timer_query_compile_stage_rewrite_with_values_ns)
        return new(timer_rego_input_parse_ns, timer_rego_query_parse_ns, timer_rego_query_compile_ns, timer_rego_query_eval_ns, timer_rego_module_parse_ns, timer_rego_module_compile_ns, timer_server_handler_ns, timer_server_read_bytes_ns, counter_server_query_cache_hit, timer_query_compile_stage_build_comprehension_index_ns, timer_query_compile_stage_check_safety_ns, timer_query_compile_stage_check_types_ns, timer_query_compile_stage_check_undefined_funcs_ns, timer_query_compile_stage_check_unsafe_builtins_ns, timer_query_compile_stage_resolve_refs_ns, timer_query_compile_stage_rewrite_comprehension_terms_ns, timer_query_compile_stage_rewrite_dynamic_terms_ns, timer_query_compile_stage_rewrite_expr_terms_ns, timer_query_compile_stage_rewrite_local_vars_ns, timer_query_compile_stage_rewrite_to_capture_value_ns, timer_query_compile_stage_rewrite_with_values_ns, )
    end
end # type Response200MetricsMetrics

const _property_types_Response200MetricsMetrics = Dict{Symbol,String}(Symbol("timer_rego_input_parse_ns")=>"Float64", Symbol("timer_rego_query_parse_ns")=>"Float64", Symbol("timer_rego_query_compile_ns")=>"Float64", Symbol("timer_rego_query_eval_ns")=>"Float64", Symbol("timer_rego_module_parse_ns")=>"Float64", Symbol("timer_rego_module_compile_ns")=>"Float64", Symbol("timer_server_handler_ns")=>"Float64", Symbol("timer_server_read_bytes_ns")=>"Float64", Symbol("counter_server_query_cache_hit")=>"Float64", Symbol("timer_query_compile_stage_build_comprehension_index_ns")=>"Float64", Symbol("timer_query_compile_stage_check_safety_ns")=>"Float64", Symbol("timer_query_compile_stage_check_types_ns")=>"Float64", Symbol("timer_query_compile_stage_check_undefined_funcs_ns")=>"Float64", Symbol("timer_query_compile_stage_check_unsafe_builtins_ns")=>"Float64", Symbol("timer_query_compile_stage_resolve_refs_ns")=>"Float64", Symbol("timer_query_compile_stage_rewrite_comprehension_terms_ns")=>"Float64", Symbol("timer_query_compile_stage_rewrite_dynamic_terms_ns")=>"Float64", Symbol("timer_query_compile_stage_rewrite_expr_terms_ns")=>"Float64", Symbol("timer_query_compile_stage_rewrite_local_vars_ns")=>"Float64", Symbol("timer_query_compile_stage_rewrite_to_capture_value_ns")=>"Float64", Symbol("timer_query_compile_stage_rewrite_with_values_ns")=>"Float64", )
OpenAPI.property_type(::Type{ Response200MetricsMetrics }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_Response200MetricsMetrics[name]))}

function check_required(o::Response200MetricsMetrics)
    true
end

function OpenAPI.validate_property(::Type{ Response200MetricsMetrics }, name::Symbol, val)
end
