# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""getDocumentSuccessResponse

    GetDocumentSuccessResponse(;
        result=nothing,
        decision_id=nothing,
        metrics=nothing,
    )

    - result::Any : The result of the query. Can be whatever type the query returns - bool, number, string, array, json.
    - decision_id::String
    - metrics::Dict{String, Any}
"""
Base.@kwdef mutable struct GetDocumentSuccessResponse <: OpenAPI.APIModel
    result::Union{Nothing, Any} = nothing
    decision_id::Union{Nothing, String} = nothing
    metrics::Union{Nothing, Dict{String, Any}} = nothing

    function GetDocumentSuccessResponse(result, decision_id, metrics, )
        OpenAPI.validate_property(GetDocumentSuccessResponse, Symbol("result"), result)
        OpenAPI.validate_property(GetDocumentSuccessResponse, Symbol("decision_id"), decision_id)
        OpenAPI.validate_property(GetDocumentSuccessResponse, Symbol("metrics"), metrics)
        return new(result, decision_id, metrics, )
    end
end # type GetDocumentSuccessResponse

const _property_types_GetDocumentSuccessResponse = Dict{Symbol,String}(Symbol("result")=>"Any", Symbol("decision_id")=>"String", Symbol("metrics")=>"Dict{String, Any}", )
OpenAPI.property_type(::Type{ GetDocumentSuccessResponse }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_GetDocumentSuccessResponse[name]))}

function check_required(o::GetDocumentSuccessResponse)
    true
end

function OpenAPI.validate_property(::Type{ GetDocumentSuccessResponse }, name::Symbol, val)
end
