# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""response200Explanations_explanation_inner_locals_inner

    Response200ExplanationsExplanationInnerLocalsInner(;
        key=nothing,
        value=nothing,
    )

    - key::Response200ExplanationsExplanationInnerLocalsInnerKey
    - value::Response200ExplanationsExplanationInnerLocalsInnerKey
"""
Base.@kwdef mutable struct Response200ExplanationsExplanationInnerLocalsInner <: OpenAPI.APIModel
    key = nothing # spec type: Union{ Nothing, Response200ExplanationsExplanationInnerLocalsInnerKey }
    value = nothing # spec type: Union{ Nothing, Response200ExplanationsExplanationInnerLocalsInnerKey }

    function Response200ExplanationsExplanationInnerLocalsInner(key, value, )
        OpenAPI.validate_property(Response200ExplanationsExplanationInnerLocalsInner, Symbol("key"), key)
        OpenAPI.validate_property(Response200ExplanationsExplanationInnerLocalsInner, Symbol("value"), value)
        return new(key, value, )
    end
end # type Response200ExplanationsExplanationInnerLocalsInner

const _property_types_Response200ExplanationsExplanationInnerLocalsInner = Dict{Symbol,String}(Symbol("key")=>"Response200ExplanationsExplanationInnerLocalsInnerKey", Symbol("value")=>"Response200ExplanationsExplanationInnerLocalsInnerKey", )
OpenAPI.property_type(::Type{ Response200ExplanationsExplanationInnerLocalsInner }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_Response200ExplanationsExplanationInnerLocalsInner[name]))}

function check_required(o::Response200ExplanationsExplanationInnerLocalsInner)
    true
end

function OpenAPI.validate_property(::Type{ Response200ExplanationsExplanationInnerLocalsInner }, name::Symbol, val)
end
