# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""policy_ast_rules_inner

    PolicyAstRulesInner(;
        head=nothing,
        body=nothing,
    )

    - head::PolicyAstRulesInnerHead
    - body::Vector{PolicyAstRulesInnerBodyInner} : A list of the terms in this rule
"""
Base.@kwdef mutable struct PolicyAstRulesInner <: OpenAPI.APIModel
    head = nothing # spec type: Union{ Nothing, PolicyAstRulesInnerHead }
    body::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{PolicyAstRulesInnerBodyInner} }

    function PolicyAstRulesInner(head, body, )
        OpenAPI.validate_property(PolicyAstRulesInner, Symbol("head"), head)
        OpenAPI.validate_property(PolicyAstRulesInner, Symbol("body"), body)
        return new(head, body, )
    end
end # type PolicyAstRulesInner

const _property_types_PolicyAstRulesInner = Dict{Symbol,String}(Symbol("head")=>"PolicyAstRulesInnerHead", Symbol("body")=>"Vector{PolicyAstRulesInnerBodyInner}", )
OpenAPI.property_type(::Type{ PolicyAstRulesInner }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_PolicyAstRulesInner[name]))}

function check_required(o::PolicyAstRulesInner)
    true
end

function OpenAPI.validate_property(::Type{ PolicyAstRulesInner }, name::Symbol, val)
end
