# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""response400_errors_inner

    Response400ErrorsInner(;
        code=nothing,
        message=nothing,
        location=nothing,
    )

    - code::String : The error code name
    - message::String : A general description of the error
    - location::Response400ErrorsInnerLocation
"""
Base.@kwdef mutable struct Response400ErrorsInner <: OpenAPI.APIModel
    code::Union{Nothing, String} = nothing
    message::Union{Nothing, String} = nothing
    location = nothing # spec type: Union{ Nothing, Response400ErrorsInnerLocation }

    function Response400ErrorsInner(code, message, location, )
        OpenAPI.validate_property(Response400ErrorsInner, Symbol("code"), code)
        OpenAPI.validate_property(Response400ErrorsInner, Symbol("message"), message)
        OpenAPI.validate_property(Response400ErrorsInner, Symbol("location"), location)
        return new(code, message, location, )
    end
end # type Response400ErrorsInner

const _property_types_Response400ErrorsInner = Dict{Symbol,String}(Symbol("code")=>"String", Symbol("message")=>"String", Symbol("location")=>"Response400ErrorsInnerLocation", )
OpenAPI.property_type(::Type{ Response400ErrorsInner }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_Response400ErrorsInner[name]))}

function check_required(o::Response400ErrorsInner)
    true
end

function OpenAPI.validate_property(::Type{ Response400ErrorsInner }, name::Symbol, val)
    if name === Symbol("code")
        OpenAPI.validate_param(name, "Response400ErrorsInner", :minLength, val, 1)
    end
    if name === Symbol("message")
        OpenAPI.validate_param(name, "Response400ErrorsInner", :minLength, val, 1)
    end
end
