# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""policy_ast_rules_inner_body_inner

    PolicyAstRulesInnerBodyInner(;
        index=nothing,
        terms=nothing,
    )

    - index::Float64 : The location of this term in the list (starts at 0)
    - terms::Any : The type/value pairing for this term
"""
Base.@kwdef mutable struct PolicyAstRulesInnerBodyInner <: OpenAPI.APIModel
    index::Union{Nothing, Float64} = nothing
    terms::Union{Nothing, Any} = nothing

    function PolicyAstRulesInnerBodyInner(index, terms, )
        OpenAPI.validate_property(PolicyAstRulesInnerBodyInner, Symbol("index"), index)
        OpenAPI.validate_property(PolicyAstRulesInnerBodyInner, Symbol("terms"), terms)
        return new(index, terms, )
    end
end # type PolicyAstRulesInnerBodyInner

const _property_types_PolicyAstRulesInnerBodyInner = Dict{Symbol,String}(Symbol("index")=>"Float64", Symbol("terms")=>"Any", )
OpenAPI.property_type(::Type{ PolicyAstRulesInnerBodyInner }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_PolicyAstRulesInnerBodyInner[name]))}

function check_required(o::PolicyAstRulesInnerBodyInner)
    true
end

function OpenAPI.validate_property(::Type{ PolicyAstRulesInnerBodyInner }, name::Symbol, val)
end
