# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""errorLocation

    ErrorLocation(;
        file=nothing,
        row=nothing,
        col=nothing,
    )

    - file::String : The policy module name that generated the error
    - row::Float64 : The line number in the policy module where the error occurred
    - col::Float64 : The column in the policy module where the error occurred
"""
Base.@kwdef mutable struct ErrorLocation <: OpenAPI.APIModel
    file::Union{Nothing, String} = nothing
    row::Union{Nothing, Float64} = nothing
    col::Union{Nothing, Float64} = nothing

    function ErrorLocation(file, row, col, )
        OpenAPI.validate_property(ErrorLocation, Symbol("file"), file)
        OpenAPI.validate_property(ErrorLocation, Symbol("row"), row)
        OpenAPI.validate_property(ErrorLocation, Symbol("col"), col)
        return new(file, row, col, )
    end
end # type ErrorLocation

const _property_types_ErrorLocation = Dict{Symbol,String}(Symbol("file")=>"String", Symbol("row")=>"Float64", Symbol("col")=>"Float64", )
OpenAPI.property_type(::Type{ ErrorLocation }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ErrorLocation[name]))}

function check_required(o::ErrorLocation)
    true
end

function OpenAPI.validate_property(::Type{ ErrorLocation }, name::Symbol, val)
end
