# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""response200Bool

    Response200Bool(;
        result=nothing,
    )

    - result::Bool
"""
Base.@kwdef mutable struct Response200Bool <: OpenAPI.APIModel
    result::Union{Nothing, Bool} = nothing

    function Response200Bool(result, )
        OpenAPI.validate_property(Response200Bool, Symbol("result"), result)
        return new(result, )
    end
end # type Response200Bool

const _property_types_Response200Bool = Dict{Symbol,String}(Symbol("result")=>"Bool", )
OpenAPI.property_type(::Type{ Response200Bool }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_Response200Bool[name]))}

function check_required(o::Response200Bool)
    true
end

function OpenAPI.validate_property(::Type{ Response200Bool }, name::Symbol, val)
end
