# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""policy_ast_rules_inner_body_inner_terms_inner_value_inner

    PolicyAstRulesInnerBodyInnerTermsInnerValueInner(;
        type=nothing,
        value=nothing,
    )

    - type::String
    - value::String
"""
Base.@kwdef mutable struct PolicyAstRulesInnerBodyInnerTermsInnerValueInner <: OpenAPI.APIModel
    type::Union{Nothing, String} = nothing
    value::Union{Nothing, String} = nothing

    function PolicyAstRulesInnerBodyInnerTermsInnerValueInner(type, value, )
        OpenAPI.validate_property(PolicyAstRulesInnerBodyInnerTermsInnerValueInner, Symbol("type"), type)
        OpenAPI.validate_property(PolicyAstRulesInnerBodyInnerTermsInnerValueInner, Symbol("value"), value)
        return new(type, value, )
    end
end # type PolicyAstRulesInnerBodyInnerTermsInnerValueInner

const _property_types_PolicyAstRulesInnerBodyInnerTermsInnerValueInner = Dict{Symbol,String}(Symbol("type")=>"String", Symbol("value")=>"String", )
OpenAPI.property_type(::Type{ PolicyAstRulesInnerBodyInnerTermsInnerValueInner }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_PolicyAstRulesInnerBodyInnerTermsInnerValueInner[name]))}

function check_required(o::PolicyAstRulesInnerBodyInnerTermsInnerValueInner)
    true
end

function OpenAPI.validate_property(::Type{ PolicyAstRulesInnerBodyInnerTermsInnerValueInner }, name::Symbol, val)
end
