# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""deleteDocumentSuccessResponse

    DeleteDocumentSuccessResponse(;
        metrics=nothing,
    )

    - metrics::Dict{String, Any}
"""
Base.@kwdef mutable struct DeleteDocumentSuccessResponse <: OpenAPI.APIModel
    metrics::Union{Nothing, Dict{String, Any}} = nothing

    function DeleteDocumentSuccessResponse(metrics, )
        OpenAPI.validate_property(DeleteDocumentSuccessResponse, Symbol("metrics"), metrics)
        return new(metrics, )
    end
end # type DeleteDocumentSuccessResponse

const _property_types_DeleteDocumentSuccessResponse = Dict{Symbol,String}(Symbol("metrics")=>"Dict{String, Any}", )
OpenAPI.property_type(::Type{ DeleteDocumentSuccessResponse }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_DeleteDocumentSuccessResponse[name]))}

function check_required(o::DeleteDocumentSuccessResponse)
    true
end

function OpenAPI.validate_property(::Type{ DeleteDocumentSuccessResponse }, name::Symbol, val)
end
