# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""policy_ast_rules_inner_head_key
The type/value pairing for this rule&#39;s head

    PolicyAstRulesInnerHeadKey(;
        type=nothing,
        value=nothing,
    )

    - type::String : The type of the head
    - value::String : The value of the head
"""
Base.@kwdef mutable struct PolicyAstRulesInnerHeadKey <: OpenAPI.APIModel
    type::Union{Nothing, String} = nothing
    value::Union{Nothing, String} = nothing

    function PolicyAstRulesInnerHeadKey(type, value, )
        OpenAPI.validate_property(PolicyAstRulesInnerHeadKey, Symbol("type"), type)
        OpenAPI.validate_property(PolicyAstRulesInnerHeadKey, Symbol("value"), value)
        return new(type, value, )
    end
end # type PolicyAstRulesInnerHeadKey

const _property_types_PolicyAstRulesInnerHeadKey = Dict{Symbol,String}(Symbol("type")=>"String", Symbol("value")=>"String", )
OpenAPI.property_type(::Type{ PolicyAstRulesInnerHeadKey }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_PolicyAstRulesInnerHeadKey[name]))}

function check_required(o::PolicyAstRulesInnerHeadKey)
    true
end

function OpenAPI.validate_property(::Type{ PolicyAstRulesInnerHeadKey }, name::Symbol, val)
end
