# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""getPolicyListSuccessResponse

    GetPolicyListSuccessResponse(;
        result=nothing,
    )

    - result::Vector{Policy}
"""
Base.@kwdef mutable struct GetPolicyListSuccessResponse <: OpenAPI.APIModel
    result::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{Policy} }

    function GetPolicyListSuccessResponse(result, )
        OpenAPI.validate_property(GetPolicyListSuccessResponse, Symbol("result"), result)
        return new(result, )
    end
end # type GetPolicyListSuccessResponse

const _property_types_GetPolicyListSuccessResponse = Dict{Symbol,String}(Symbol("result")=>"Vector{Policy}", )
OpenAPI.property_type(::Type{ GetPolicyListSuccessResponse }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_GetPolicyListSuccessResponse[name]))}

function check_required(o::GetPolicyListSuccessResponse)
    o.result === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ GetPolicyListSuccessResponse }, name::Symbol, val)
end
