# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""unhealthyResponse

    UnhealthyResponse(;
        error=nothing,
    )

    - error::String : The error message
"""
Base.@kwdef mutable struct UnhealthyResponse <: OpenAPI.APIModel
    error::Union{Nothing, String} = nothing

    function UnhealthyResponse(error, )
        OpenAPI.validate_property(UnhealthyResponse, Symbol("error"), error)
        return new(error, )
    end
end # type UnhealthyResponse

const _property_types_UnhealthyResponse = Dict{Symbol,String}(Symbol("error")=>"String", )
OpenAPI.property_type(::Type{ UnhealthyResponse }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_UnhealthyResponse[name]))}

function check_required(o::UnhealthyResponse)
    o.error === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ UnhealthyResponse }, name::Symbol, val)
end
