# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""successResult

    SuccessResult(; value=nothing)
"""
mutable struct SuccessResult <: OpenAPI.OneOfAPIModel
    value::Any # Union{ Response200Bool, Response200Result }
    SuccessResult() = new()
    SuccessResult(value) = new(value)
end # type SuccessResult

function OpenAPI.property_type(::Type{ SuccessResult }, name::Symbol, json::Dict{String,Any})
    
    # no discriminator specified, can't determine the exact type
    return fieldtype(SuccessResult, name)
end
