# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""_200Explanations_explanation_inner_node_terms_inner

    200ExplanationsExplanationInnerNodeTermsInner(;
        type=nothing,
        value=nothing,
    )

    - type::String
    - value::String
"""
Base.@kwdef mutable struct 200ExplanationsExplanationInnerNodeTermsInner <: OpenAPI.APIModel
    type::Union{Nothing, String} = nothing
    value::Union{Nothing, String} = nothing

    function 200ExplanationsExplanationInnerNodeTermsInner(type, value, )
        OpenAPI.validate_property(200ExplanationsExplanationInnerNodeTermsInner, Symbol("type"), type)
        OpenAPI.validate_property(200ExplanationsExplanationInnerNodeTermsInner, Symbol("value"), value)
        return new(type, value, )
    end
end # type 200ExplanationsExplanationInnerNodeTermsInner

const _property_types_200ExplanationsExplanationInnerNodeTermsInner = Dict{Symbol,String}(Symbol("type")=>"String", Symbol("value")=>"String", )
OpenAPI.property_type(::Type{ 200ExplanationsExplanationInnerNodeTermsInner }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_200ExplanationsExplanationInnerNodeTermsInner[name]))}

function check_required(o::200ExplanationsExplanationInnerNodeTermsInner)
    true
end

function OpenAPI.validate_property(::Type{ 200ExplanationsExplanationInnerNodeTermsInner }, name::Symbol, val)
end
