# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""response200Result_result_inner_ast
The types for declarations and runtime objects passed to your implementation. This consists of an abstract syntax tree (AST) of policy modules, package and import declarations, rules, expressions, and terms.

    Response200ResultResultInnerAst(;
        package=nothing,
        rules=nothing,
    )

    - package::Response200ResultResultInnerAstPackage
    - rules::Vector{Response200ResultResultInnerAstRulesInner} : When OPA evaluates a rule, it generates the content of a [virtual documents](https://www.openpolicyagent.org/docs/latest/philosophy/#the-opa-document-model)
"""
Base.@kwdef mutable struct Response200ResultResultInnerAst <: OpenAPI.APIModel
    package = nothing # spec type: Union{ Nothing, Response200ResultResultInnerAstPackage }
    rules::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{Response200ResultResultInnerAstRulesInner} }

    function Response200ResultResultInnerAst(package, rules, )
        OpenAPI.validate_property(Response200ResultResultInnerAst, Symbol("package"), package)
        OpenAPI.validate_property(Response200ResultResultInnerAst, Symbol("rules"), rules)
        return new(package, rules, )
    end
end # type Response200ResultResultInnerAst

const _property_types_Response200ResultResultInnerAst = Dict{Symbol,String}(Symbol("package")=>"Response200ResultResultInnerAstPackage", Symbol("rules")=>"Vector{Response200ResultResultInnerAstRulesInner}", )
OpenAPI.property_type(::Type{ Response200ResultResultInnerAst }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_Response200ResultResultInnerAst[name]))}

function check_required(o::Response200ResultResultInnerAst)
    true
end

function OpenAPI.validate_property(::Type{ Response200ResultResultInnerAst }, name::Symbol, val)
    if name === Symbol("rules")
        OpenAPI.validate_param(name, "Response200ResultResultInnerAst", :uniqueItems, val, true)
    end
end
