# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""response200Provenance

    Response200Provenance(;
        provenance=nothing,
    )

    - provenance::Response200ProvenanceProvenance
"""
Base.@kwdef mutable struct Response200Provenance <: OpenAPI.APIModel
    provenance = nothing # spec type: Union{ Nothing, Response200ProvenanceProvenance }

    function Response200Provenance(provenance, )
        OpenAPI.validate_property(Response200Provenance, Symbol("provenance"), provenance)
        return new(provenance, )
    end
end # type Response200Provenance

const _property_types_Response200Provenance = Dict{Symbol,String}(Symbol("provenance")=>"Response200ProvenanceProvenance", )
OpenAPI.property_type(::Type{ Response200Provenance }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_Response200Provenance[name]))}

function check_required(o::Response200Provenance)
    true
end

function OpenAPI.validate_property(::Type{ Response200Provenance }, name::Symbol, val)
end
