# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""_200SingleResult_result_keys
Keys

    200SingleResultResultKeys(;
        var"global-key"=nothing,
    )

    - var"global-key"::200SingleResultResultKeysGlobalKey
"""
Base.@kwdef mutable struct 200SingleResultResultKeys <: OpenAPI.APIModel
    var"global-key" = nothing # spec type: Union{ Nothing, 200SingleResultResultKeysGlobalKey }

    function 200SingleResultResultKeys(var"global-key", )
        OpenAPI.validate_property(200SingleResultResultKeys, Symbol("global-key"), var"global-key")
        return new(var"global-key", )
    end
end # type 200SingleResultResultKeys

const _property_types_200SingleResultResultKeys = Dict{Symbol,String}(Symbol("global-key")=>"200SingleResultResultKeysGlobalKey", )
OpenAPI.property_type(::Type{ 200SingleResultResultKeys }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_200SingleResultResultKeys[name]))}

function check_required(o::200SingleResultResultKeys)
    true
end

function OpenAPI.validate_property(::Type{ 200SingleResultResultKeys }, name::Symbol, val)
end
