# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""_200Result_result_inner_ast_package

    200ResultResultInnerAstPackage(;
        path=nothing,
    )

    - path::Vector{200ResultResultInnerAstPackagePathInner} : The path to the package
"""
Base.@kwdef mutable struct 200ResultResultInnerAstPackage <: OpenAPI.APIModel
    path::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{200ResultResultInnerAstPackagePathInner} }

    function 200ResultResultInnerAstPackage(path, )
        OpenAPI.validate_property(200ResultResultInnerAstPackage, Symbol("path"), path)
        return new(path, )
    end
end # type 200ResultResultInnerAstPackage

const _property_types_200ResultResultInnerAstPackage = Dict{Symbol,String}(Symbol("path")=>"Vector{200ResultResultInnerAstPackagePathInner}", )
OpenAPI.property_type(::Type{ 200ResultResultInnerAstPackage }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_200ResultResultInnerAstPackage[name]))}

function check_required(o::200ResultResultInnerAstPackage)
    true
end

function OpenAPI.validate_property(::Type{ 200ResultResultInnerAstPackage }, name::Symbol, val)
end
