# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""200Explanations

    Model200Explanations(;
        explanation=nothing,
    )

    - explanation::Vector{200ExplanationsExplanationInner}
"""
Base.@kwdef mutable struct Model200Explanations <: OpenAPI.APIModel
    explanation::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{200ExplanationsExplanationInner} }

    function Model200Explanations(explanation, )
        OpenAPI.validate_property(Model200Explanations, Symbol("explanation"), explanation)
        return new(explanation, )
    end
end # type Model200Explanations

const _property_types_Model200Explanations = Dict{Symbol,String}(Symbol("explanation")=>"Vector{200ExplanationsExplanationInner}", )
OpenAPI.property_type(::Type{ Model200Explanations }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_Model200Explanations[name]))}

function check_required(o::Model200Explanations)
    true
end

function OpenAPI.validate_property(::Type{ Model200Explanations }, name::Symbol, val)
end
