# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""response200Result_result_inner_ast_rules_inner_head

    Response200ResultResultInnerAstRulesInnerHead(;
        name=nothing,
        key=nothing,
    )

    - name::String : The head of the rule
    - key::Response200ResultResultInnerAstRulesInnerHeadKey
"""
Base.@kwdef mutable struct Response200ResultResultInnerAstRulesInnerHead <: OpenAPI.APIModel
    name::Union{Nothing, String} = nothing
    key = nothing # spec type: Union{ Nothing, Response200ResultResultInnerAstRulesInnerHeadKey }

    function Response200ResultResultInnerAstRulesInnerHead(name, key, )
        OpenAPI.validate_property(Response200ResultResultInnerAstRulesInnerHead, Symbol("name"), name)
        OpenAPI.validate_property(Response200ResultResultInnerAstRulesInnerHead, Symbol("key"), key)
        return new(name, key, )
    end
end # type Response200ResultResultInnerAstRulesInnerHead

const _property_types_Response200ResultResultInnerAstRulesInnerHead = Dict{Symbol,String}(Symbol("name")=>"String", Symbol("key")=>"Response200ResultResultInnerAstRulesInnerHeadKey", )
OpenAPI.property_type(::Type{ Response200ResultResultInnerAstRulesInnerHead }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_Response200ResultResultInnerAstRulesInnerHead[name]))}

function check_required(o::Response200ResultResultInnerAstRulesInnerHead)
    true
end

function OpenAPI.validate_property(::Type{ Response200ResultResultInnerAstRulesInnerHead }, name::Symbol, val)
end
