# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""response200SingleResult_result

    Response200SingleResultResult(;
        services=nothing,
        labels=nothing,
        keys=nothing,
        decision_logs=nothing,
        status=nothing,
        bundles=nothing,
        default_authorization_decision=nothing,
        default_decision=nothing,
    )

    - services::Response200SingleResultResultServices
    - labels::Response200SingleResultResultLabels
    - keys::Response200SingleResultResultKeys
    - decision_logs::Response200SingleResultResultDecisionLogs
    - status::Response200SingleResultResultStatus
    - bundles::Response200SingleResultResultBundles
    - default_authorization_decision::String
    - default_decision::String
"""
Base.@kwdef mutable struct Response200SingleResultResult <: OpenAPI.APIModel
    services = nothing # spec type: Union{ Nothing, Response200SingleResultResultServices }
    labels = nothing # spec type: Union{ Nothing, Response200SingleResultResultLabels }
    keys = nothing # spec type: Union{ Nothing, Response200SingleResultResultKeys }
    decision_logs = nothing # spec type: Union{ Nothing, Response200SingleResultResultDecisionLogs }
    status = nothing # spec type: Union{ Nothing, Response200SingleResultResultStatus }
    bundles = nothing # spec type: Union{ Nothing, Response200SingleResultResultBundles }
    default_authorization_decision::Union{Nothing, String} = nothing
    default_decision::Union{Nothing, String} = nothing

    function Response200SingleResultResult(services, labels, keys, decision_logs, status, bundles, default_authorization_decision, default_decision, )
        OpenAPI.validate_property(Response200SingleResultResult, Symbol("services"), services)
        OpenAPI.validate_property(Response200SingleResultResult, Symbol("labels"), labels)
        OpenAPI.validate_property(Response200SingleResultResult, Symbol("keys"), keys)
        OpenAPI.validate_property(Response200SingleResultResult, Symbol("decision_logs"), decision_logs)
        OpenAPI.validate_property(Response200SingleResultResult, Symbol("status"), status)
        OpenAPI.validate_property(Response200SingleResultResult, Symbol("bundles"), bundles)
        OpenAPI.validate_property(Response200SingleResultResult, Symbol("default_authorization_decision"), default_authorization_decision)
        OpenAPI.validate_property(Response200SingleResultResult, Symbol("default_decision"), default_decision)
        return new(services, labels, keys, decision_logs, status, bundles, default_authorization_decision, default_decision, )
    end
end # type Response200SingleResultResult

const _property_types_Response200SingleResultResult = Dict{Symbol,String}(Symbol("services")=>"Response200SingleResultResultServices", Symbol("labels")=>"Response200SingleResultResultLabels", Symbol("keys")=>"Response200SingleResultResultKeys", Symbol("decision_logs")=>"Response200SingleResultResultDecisionLogs", Symbol("status")=>"Response200SingleResultResultStatus", Symbol("bundles")=>"Response200SingleResultResultBundles", Symbol("default_authorization_decision")=>"String", Symbol("default_decision")=>"String", )
OpenAPI.property_type(::Type{ Response200SingleResultResult }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_Response200SingleResultResult[name]))}

function check_required(o::Response200SingleResultResult)
    true
end

function OpenAPI.validate_property(::Type{ Response200SingleResultResult }, name::Symbol, val)
end
