# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""_200Explanations_explanation_inner_node
The AST element associated with the evaluation step.

    200ExplanationsExplanationInnerNode(;
        index=nothing,
        terms=nothing,
    )

    - index::Float64 : Node number
    - terms::Vector{200ExplanationsExplanationInnerNodeTermsInner}
"""
Base.@kwdef mutable struct 200ExplanationsExplanationInnerNode <: OpenAPI.APIModel
    index::Union{Nothing, Float64} = nothing
    terms::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{200ExplanationsExplanationInnerNodeTermsInner} }

    function 200ExplanationsExplanationInnerNode(index, terms, )
        OpenAPI.validate_property(200ExplanationsExplanationInnerNode, Symbol("index"), index)
        OpenAPI.validate_property(200ExplanationsExplanationInnerNode, Symbol("terms"), terms)
        return new(index, terms, )
    end
end # type 200ExplanationsExplanationInnerNode

const _property_types_200ExplanationsExplanationInnerNode = Dict{Symbol,String}(Symbol("index")=>"Float64", Symbol("terms")=>"Vector{200ExplanationsExplanationInnerNodeTermsInner}", )
OpenAPI.property_type(::Type{ 200ExplanationsExplanationInnerNode }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_200ExplanationsExplanationInnerNode[name]))}

function check_required(o::200ExplanationsExplanationInnerNode)
    true
end

function OpenAPI.validate_property(::Type{ 200ExplanationsExplanationInnerNode }, name::Symbol, val)
end
