# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""response200Metrics

    Response200Metrics(;
        metrics=nothing,
    )

    - metrics::Response200MetricsMetrics
"""
Base.@kwdef mutable struct Response200Metrics <: OpenAPI.APIModel
    metrics = nothing # spec type: Union{ Nothing, Response200MetricsMetrics }

    function Response200Metrics(metrics, )
        OpenAPI.validate_property(Response200Metrics, Symbol("metrics"), metrics)
        return new(metrics, )
    end
end # type Response200Metrics

const _property_types_Response200Metrics = Dict{Symbol,String}(Symbol("metrics")=>"Response200MetricsMetrics", )
OpenAPI.property_type(::Type{ Response200Metrics }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_Response200Metrics[name]))}

function check_required(o::Response200Metrics)
    true
end

function OpenAPI.validate_property(::Type{ Response200Metrics }, name::Symbol, val)
end
