# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""_200Result_result_inner_ast_rules_inner_head

    200ResultResultInnerAstRulesInnerHead(;
        name=nothing,
        key=nothing,
    )

    - name::String : The head of the rule
    - key::200ResultResultInnerAstRulesInnerHeadKey
"""
Base.@kwdef mutable struct 200ResultResultInnerAstRulesInnerHead <: OpenAPI.APIModel
    name::Union{Nothing, String} = nothing
    key = nothing # spec type: Union{ Nothing, 200ResultResultInnerAstRulesInnerHeadKey }

    function 200ResultResultInnerAstRulesInnerHead(name, key, )
        OpenAPI.validate_property(200ResultResultInnerAstRulesInnerHead, Symbol("name"), name)
        OpenAPI.validate_property(200ResultResultInnerAstRulesInnerHead, Symbol("key"), key)
        return new(name, key, )
    end
end # type 200ResultResultInnerAstRulesInnerHead

const _property_types_200ResultResultInnerAstRulesInnerHead = Dict{Symbol,String}(Symbol("name")=>"String", Symbol("key")=>"200ResultResultInnerAstRulesInnerHeadKey", )
OpenAPI.property_type(::Type{ 200ResultResultInnerAstRulesInnerHead }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_200ResultResultInnerAstRulesInnerHead[name]))}

function check_required(o::200ResultResultInnerAstRulesInnerHead)
    true
end

function OpenAPI.validate_property(::Type{ 200ResultResultInnerAstRulesInnerHead }, name::Symbol, val)
end
