# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""_200SingleResult_result_decision_logs
Logs

    200SingleResultResultDecisionLogs(;
        service=nothing,
    )

    - service::String : Service
"""
Base.@kwdef mutable struct 200SingleResultResultDecisionLogs <: OpenAPI.APIModel
    service::Union{Nothing, String} = nothing

    function 200SingleResultResultDecisionLogs(service, )
        OpenAPI.validate_property(200SingleResultResultDecisionLogs, Symbol("service"), service)
        return new(service, )
    end
end # type 200SingleResultResultDecisionLogs

const _property_types_200SingleResultResultDecisionLogs = Dict{Symbol,String}(Symbol("service")=>"String", )
OpenAPI.property_type(::Type{ 200SingleResultResultDecisionLogs }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_200SingleResultResultDecisionLogs[name]))}

function check_required(o::200SingleResultResultDecisionLogs)
    true
end

function OpenAPI.validate_property(::Type{ 200SingleResultResultDecisionLogs }, name::Symbol, val)
    if name === Symbol("service")
        OpenAPI.validate_param(name, "200SingleResultResultDecisionLogs", :minLength, val, 1)
    end
end
