# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""_200Explanations_explanation_inner_locals_inner

    200ExplanationsExplanationInnerLocalsInner(;
        key=nothing,
        value=nothing,
    )

    - key::200ExplanationsExplanationInnerLocalsInnerKey
    - value::200ExplanationsExplanationInnerLocalsInnerKey
"""
Base.@kwdef mutable struct 200ExplanationsExplanationInnerLocalsInner <: OpenAPI.APIModel
    key = nothing # spec type: Union{ Nothing, 200ExplanationsExplanationInnerLocalsInnerKey }
    value = nothing # spec type: Union{ Nothing, 200ExplanationsExplanationInnerLocalsInnerKey }

    function 200ExplanationsExplanationInnerLocalsInner(key, value, )
        OpenAPI.validate_property(200ExplanationsExplanationInnerLocalsInner, Symbol("key"), key)
        OpenAPI.validate_property(200ExplanationsExplanationInnerLocalsInner, Symbol("value"), value)
        return new(key, value, )
    end
end # type 200ExplanationsExplanationInnerLocalsInner

const _property_types_200ExplanationsExplanationInnerLocalsInner = Dict{Symbol,String}(Symbol("key")=>"200ExplanationsExplanationInnerLocalsInnerKey", Symbol("value")=>"200ExplanationsExplanationInnerLocalsInnerKey", )
OpenAPI.property_type(::Type{ 200ExplanationsExplanationInnerLocalsInner }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_200ExplanationsExplanationInnerLocalsInner[name]))}

function check_required(o::200ExplanationsExplanationInnerLocalsInner)
    true
end

function OpenAPI.validate_property(::Type{ 200ExplanationsExplanationInnerLocalsInner }, name::Symbol, val)
end
