# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""response200Result_result_inner_ast_rules_inner_body_inner_terms_inner_value_inner

    Response200ResultResultInnerAstRulesInnerBodyInnerTermsInnerValueInner(;
        type=nothing,
        value=nothing,
    )

    - type::String
    - value::String
"""
Base.@kwdef mutable struct Response200ResultResultInnerAstRulesInnerBodyInnerTermsInnerValueInner <: OpenAPI.APIModel
    type::Union{Nothing, String} = nothing
    value::Union{Nothing, String} = nothing

    function Response200ResultResultInnerAstRulesInnerBodyInnerTermsInnerValueInner(type, value, )
        OpenAPI.validate_property(Response200ResultResultInnerAstRulesInnerBodyInnerTermsInnerValueInner, Symbol("type"), type)
        OpenAPI.validate_property(Response200ResultResultInnerAstRulesInnerBodyInnerTermsInnerValueInner, Symbol("value"), value)
        return new(type, value, )
    end
end # type Response200ResultResultInnerAstRulesInnerBodyInnerTermsInnerValueInner

const _property_types_Response200ResultResultInnerAstRulesInnerBodyInnerTermsInnerValueInner = Dict{Symbol,String}(Symbol("type")=>"String", Symbol("value")=>"String", )
OpenAPI.property_type(::Type{ Response200ResultResultInnerAstRulesInnerBodyInnerTermsInnerValueInner }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_Response200ResultResultInnerAstRulesInnerBodyInnerTermsInnerValueInner[name]))}

function check_required(o::Response200ResultResultInnerAstRulesInnerBodyInnerTermsInnerValueInner)
    true
end

function OpenAPI.validate_property(::Type{ Response200ResultResultInnerAstRulesInnerBodyInnerTermsInnerValueInner }, name::Symbol, val)
end
