# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""400

    Model400(;
        code=nothing,
        message=nothing,
        errors=nothing,
    )

    - code::String : The error code name
    - message::String : The description of the error
    - errors::Vector{400ErrorsInner} : Errors that may have been generated during the parse, compile, or installation of a policy module
"""
Base.@kwdef mutable struct Model400 <: OpenAPI.APIModel
    code::Union{Nothing, String} = nothing
    message::Union{Nothing, String} = nothing
    errors::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{400ErrorsInner} }

    function Model400(code, message, errors, )
        OpenAPI.validate_property(Model400, Symbol("code"), code)
        OpenAPI.validate_property(Model400, Symbol("message"), message)
        OpenAPI.validate_property(Model400, Symbol("errors"), errors)
        return new(code, message, errors, )
    end
end # type Model400

const _property_types_Model400 = Dict{Symbol,String}(Symbol("code")=>"String", Symbol("message")=>"String", Symbol("errors")=>"Vector{400ErrorsInner}", )
OpenAPI.property_type(::Type{ Model400 }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_Model400[name]))}

function check_required(o::Model400)
    o.code === nothing && (return false)
    o.message === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ Model400 }, name::Symbol, val)
    if name === Symbol("code")
        OpenAPI.validate_param(name, "Model400", :minLength, val, 1)
    end
    if name === Symbol("message")
        OpenAPI.validate_param(name, "Model400", :minLength, val, 1)
    end
    if name === Symbol("errors")
        OpenAPI.validate_param(name, "Model400", :uniqueItems, val, true)
    end
end
