# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""200Provenance

    Model200Provenance(;
        provenance=nothing,
    )

    - provenance::200ProvenanceProvenance
"""
Base.@kwdef mutable struct Model200Provenance <: OpenAPI.APIModel
    provenance = nothing # spec type: Union{ Nothing, 200ProvenanceProvenance }

    function Model200Provenance(provenance, )
        OpenAPI.validate_property(Model200Provenance, Symbol("provenance"), provenance)
        return new(provenance, )
    end
end # type Model200Provenance

const _property_types_Model200Provenance = Dict{Symbol,String}(Symbol("provenance")=>"200ProvenanceProvenance", )
OpenAPI.property_type(::Type{ Model200Provenance }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_Model200Provenance[name]))}

function check_required(o::Model200Provenance)
    true
end

function OpenAPI.validate_property(::Type{ Model200Provenance }, name::Symbol, val)
end
