# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""200SingleResult

    Model200SingleResult(;
        result=nothing,
    )

    - result::200SingleResultResult
"""
Base.@kwdef mutable struct Model200SingleResult <: OpenAPI.APIModel
    result = nothing # spec type: Union{ Nothing, 200SingleResultResult }

    function Model200SingleResult(result, )
        OpenAPI.validate_property(Model200SingleResult, Symbol("result"), result)
        return new(result, )
    end
end # type Model200SingleResult

const _property_types_Model200SingleResult = Dict{Symbol,String}(Symbol("result")=>"200SingleResultResult", )
OpenAPI.property_type(::Type{ Model200SingleResult }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_Model200SingleResult[name]))}

function check_required(o::Model200SingleResult)
    true
end

function OpenAPI.validate_property(::Type{ Model200SingleResult }, name::Symbol, val)
end
