# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""response200SingleResult_result_services_acmecorp

    Response200SingleResultResultServicesAcmecorp(;
        url=nothing,
    )

    - url::String
"""
Base.@kwdef mutable struct Response200SingleResultResultServicesAcmecorp <: OpenAPI.APIModel
    url::Union{Nothing, String} = nothing

    function Response200SingleResultResultServicesAcmecorp(url, )
        OpenAPI.validate_property(Response200SingleResultResultServicesAcmecorp, Symbol("url"), url)
        return new(url, )
    end
end # type Response200SingleResultResultServicesAcmecorp

const _property_types_Response200SingleResultResultServicesAcmecorp = Dict{Symbol,String}(Symbol("url")=>"String", )
OpenAPI.property_type(::Type{ Response200SingleResultResultServicesAcmecorp }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_Response200SingleResultResultServicesAcmecorp[name]))}

function check_required(o::Response200SingleResultResultServicesAcmecorp)
    true
end

function OpenAPI.validate_property(::Type{ Response200SingleResultResultServicesAcmecorp }, name::Symbol, val)
end
