# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""_200SingleResult_result_services
The types of services

    200SingleResultResultServices(;
        acmecorp=nothing,
    )

    - acmecorp::200SingleResultResultServicesAcmecorp
"""
Base.@kwdef mutable struct 200SingleResultResultServices <: OpenAPI.APIModel
    acmecorp = nothing # spec type: Union{ Nothing, 200SingleResultResultServicesAcmecorp }

    function 200SingleResultResultServices(acmecorp, )
        OpenAPI.validate_property(200SingleResultResultServices, Symbol("acmecorp"), acmecorp)
        return new(acmecorp, )
    end
end # type 200SingleResultResultServices

const _property_types_200SingleResultResultServices = Dict{Symbol,String}(Symbol("acmecorp")=>"200SingleResultResultServicesAcmecorp", )
OpenAPI.property_type(::Type{ 200SingleResultResultServices }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_200SingleResultResultServices[name]))}

function check_required(o::200SingleResultResultServices)
    true
end

function OpenAPI.validate_property(::Type{ 200SingleResultResultServices }, name::Symbol, val)
end
