# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""_200SingleResult_result_bundles_authz
Auth

    200SingleResultResultBundlesAuthz(;
        service=nothing,
    )

    - service::String : Service
"""
Base.@kwdef mutable struct 200SingleResultResultBundlesAuthz <: OpenAPI.APIModel
    service::Union{Nothing, String} = nothing

    function 200SingleResultResultBundlesAuthz(service, )
        OpenAPI.validate_property(200SingleResultResultBundlesAuthz, Symbol("service"), service)
        return new(service, )
    end
end # type 200SingleResultResultBundlesAuthz

const _property_types_200SingleResultResultBundlesAuthz = Dict{Symbol,String}(Symbol("service")=>"String", )
OpenAPI.property_type(::Type{ 200SingleResultResultBundlesAuthz }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_200SingleResultResultBundlesAuthz[name]))}

function check_required(o::200SingleResultResultBundlesAuthz)
    true
end

function OpenAPI.validate_property(::Type{ 200SingleResultResultBundlesAuthz }, name::Symbol, val)
    if name === Symbol("service")
        OpenAPI.validate_param(name, "200SingleResultResultBundlesAuthz", :minLength, val, 1)
    end
end
