# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""_200SingleResult_result_status
Status

    200SingleResultResultStatus(;
        service=nothing,
    )

    - service::String : Service
"""
Base.@kwdef mutable struct 200SingleResultResultStatus <: OpenAPI.APIModel
    service::Union{Nothing, String} = nothing

    function 200SingleResultResultStatus(service, )
        OpenAPI.validate_property(200SingleResultResultStatus, Symbol("service"), service)
        return new(service, )
    end
end # type 200SingleResultResultStatus

const _property_types_200SingleResultResultStatus = Dict{Symbol,String}(Symbol("service")=>"String", )
OpenAPI.property_type(::Type{ 200SingleResultResultStatus }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_200SingleResultResultStatus[name]))}

function check_required(o::200SingleResultResultStatus)
    true
end

function OpenAPI.validate_property(::Type{ 200SingleResultResultStatus }, name::Symbol, val)
    if name === Symbol("service")
        OpenAPI.validate_param(name, "200SingleResultResultStatus", :minLength, val, 1)
    end
end
