# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""_200Explanations_explanation_inner_locals_inner_key

    200ExplanationsExplanationInnerLocalsInnerKey(;
        type=nothing,
        value=nothing,
    )

    - type::String
    - value::String
"""
Base.@kwdef mutable struct 200ExplanationsExplanationInnerLocalsInnerKey <: OpenAPI.APIModel
    type::Union{Nothing, String} = nothing
    value::Union{Nothing, String} = nothing

    function 200ExplanationsExplanationInnerLocalsInnerKey(type, value, )
        OpenAPI.validate_property(200ExplanationsExplanationInnerLocalsInnerKey, Symbol("type"), type)
        OpenAPI.validate_property(200ExplanationsExplanationInnerLocalsInnerKey, Symbol("value"), value)
        return new(type, value, )
    end
end # type 200ExplanationsExplanationInnerLocalsInnerKey

const _property_types_200ExplanationsExplanationInnerLocalsInnerKey = Dict{Symbol,String}(Symbol("type")=>"String", Symbol("value")=>"String", )
OpenAPI.property_type(::Type{ 200ExplanationsExplanationInnerLocalsInnerKey }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_200ExplanationsExplanationInnerLocalsInnerKey[name]))}

function check_required(o::200ExplanationsExplanationInnerLocalsInnerKey)
    true
end

function OpenAPI.validate_property(::Type{ 200ExplanationsExplanationInnerLocalsInnerKey }, name::Symbol, val)
end
