# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""response200Result_result_inner_ast_rules_inner_body_inner

    Response200ResultResultInnerAstRulesInnerBodyInner(;
        index=nothing,
        terms=nothing,
    )

    - index::Float64 : The location of this term in the list (starts at 0)
    - terms::Vector{Response200ResultResultInnerAstRulesInnerBodyInnerTermsInner} : The type/value pairing for this term
"""
Base.@kwdef mutable struct Response200ResultResultInnerAstRulesInnerBodyInner <: OpenAPI.APIModel
    index::Union{Nothing, Float64} = nothing
    terms::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{Response200ResultResultInnerAstRulesInnerBodyInnerTermsInner} }

    function Response200ResultResultInnerAstRulesInnerBodyInner(index, terms, )
        OpenAPI.validate_property(Response200ResultResultInnerAstRulesInnerBodyInner, Symbol("index"), index)
        OpenAPI.validate_property(Response200ResultResultInnerAstRulesInnerBodyInner, Symbol("terms"), terms)
        return new(index, terms, )
    end
end # type Response200ResultResultInnerAstRulesInnerBodyInner

const _property_types_Response200ResultResultInnerAstRulesInnerBodyInner = Dict{Symbol,String}(Symbol("index")=>"Float64", Symbol("terms")=>"Vector{Response200ResultResultInnerAstRulesInnerBodyInnerTermsInner}", )
OpenAPI.property_type(::Type{ Response200ResultResultInnerAstRulesInnerBodyInner }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_Response200ResultResultInnerAstRulesInnerBodyInner[name]))}

function check_required(o::Response200ResultResultInnerAstRulesInnerBodyInner)
    true
end

function OpenAPI.validate_property(::Type{ Response200ResultResultInnerAstRulesInnerBodyInner }, name::Symbol, val)
end
