# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""_200Result_result_inner_ast_rules_inner_body_inner_terms_inner

    200ResultResultInnerAstRulesInnerBodyInnerTermsInner(;
        type=nothing,
        value=nothing,
    )

    - type::String : The type of the term variable
    - value::Vector{200ResultResultInnerAstRulesInnerBodyInnerTermsInnerValueInner} : The list of types and values for the term variable
"""
Base.@kwdef mutable struct 200ResultResultInnerAstRulesInnerBodyInnerTermsInner <: OpenAPI.APIModel
    type::Union{Nothing, String} = nothing
    value::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{200ResultResultInnerAstRulesInnerBodyInnerTermsInnerValueInner} }

    function 200ResultResultInnerAstRulesInnerBodyInnerTermsInner(type, value, )
        OpenAPI.validate_property(200ResultResultInnerAstRulesInnerBodyInnerTermsInner, Symbol("type"), type)
        OpenAPI.validate_property(200ResultResultInnerAstRulesInnerBodyInnerTermsInner, Symbol("value"), value)
        return new(type, value, )
    end
end # type 200ResultResultInnerAstRulesInnerBodyInnerTermsInner

const _property_types_200ResultResultInnerAstRulesInnerBodyInnerTermsInner = Dict{Symbol,String}(Symbol("type")=>"String", Symbol("value")=>"Vector{200ResultResultInnerAstRulesInnerBodyInnerTermsInnerValueInner}", )
OpenAPI.property_type(::Type{ 200ResultResultInnerAstRulesInnerBodyInnerTermsInner }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_200ResultResultInnerAstRulesInnerBodyInnerTermsInner[name]))}

function check_required(o::200ResultResultInnerAstRulesInnerBodyInnerTermsInner)
    true
end

function OpenAPI.validate_property(::Type{ 200ResultResultInnerAstRulesInnerBodyInnerTermsInner }, name::Symbol, val)
end
