# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""_200SingleResult_result_services_acmecorp

    200SingleResultResultServicesAcmecorp(;
        url=nothing,
    )

    - url::String
"""
Base.@kwdef mutable struct 200SingleResultResultServicesAcmecorp <: OpenAPI.APIModel
    url::Union{Nothing, String} = nothing

    function 200SingleResultResultServicesAcmecorp(url, )
        OpenAPI.validate_property(200SingleResultResultServicesAcmecorp, Symbol("url"), url)
        return new(url, )
    end
end # type 200SingleResultResultServicesAcmecorp

const _property_types_200SingleResultResultServicesAcmecorp = Dict{Symbol,String}(Symbol("url")=>"String", )
OpenAPI.property_type(::Type{ 200SingleResultResultServicesAcmecorp }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_200SingleResultResultServicesAcmecorp[name]))}

function check_required(o::200SingleResultResultServicesAcmecorp)
    true
end

function OpenAPI.validate_property(::Type{ 200SingleResultResultServicesAcmecorp }, name::Symbol, val)
end
