# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""_400_errors_inner_location
Where the error occurred

    400ErrorsInnerLocation(;
        file=nothing,
        row=nothing,
        col=nothing,
    )

    - file::String : The policy module name that generated the error
    - row::Float64 : The line number in the policy module where the error occurred
    - col::Float64 : The column in the policy module where the error occurred
"""
Base.@kwdef mutable struct 400ErrorsInnerLocation <: OpenAPI.APIModel
    file::Union{Nothing, String} = nothing
    row::Union{Nothing, Float64} = nothing
    col::Union{Nothing, Float64} = nothing

    function 400ErrorsInnerLocation(file, row, col, )
        OpenAPI.validate_property(400ErrorsInnerLocation, Symbol("file"), file)
        OpenAPI.validate_property(400ErrorsInnerLocation, Symbol("row"), row)
        OpenAPI.validate_property(400ErrorsInnerLocation, Symbol("col"), col)
        return new(file, row, col, )
    end
end # type 400ErrorsInnerLocation

const _property_types_400ErrorsInnerLocation = Dict{Symbol,String}(Symbol("file")=>"String", Symbol("row")=>"Float64", Symbol("col")=>"Float64", )
OpenAPI.property_type(::Type{ 400ErrorsInnerLocation }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_400ErrorsInnerLocation[name]))}

function check_required(o::400ErrorsInnerLocation)
    true
end

function OpenAPI.validate_property(::Type{ 400ErrorsInnerLocation }, name::Symbol, val)
end
