# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""200Result

    Model200Result(;
        result=nothing,
    )

    - result::Vector{200ResultResultInner}
"""
Base.@kwdef mutable struct Model200Result <: OpenAPI.APIModel
    result::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{200ResultResultInner} }

    function Model200Result(result, )
        OpenAPI.validate_property(Model200Result, Symbol("result"), result)
        return new(result, )
    end
end # type Model200Result

const _property_types_Model200Result = Dict{Symbol,String}(Symbol("result")=>"Vector{200ResultResultInner}", )
OpenAPI.property_type(::Type{ Model200Result }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_Model200Result[name]))}

function check_required(o::Model200Result)
    true
end

function OpenAPI.validate_property(::Type{ Model200Result }, name::Symbol, val)
end
