# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""200Metrics

    Model200Metrics(;
        metrics=nothing,
    )

    - metrics::200MetricsMetrics
"""
Base.@kwdef mutable struct Model200Metrics <: OpenAPI.APIModel
    metrics = nothing # spec type: Union{ Nothing, 200MetricsMetrics }

    function Model200Metrics(metrics, )
        OpenAPI.validate_property(Model200Metrics, Symbol("metrics"), metrics)
        return new(metrics, )
    end
end # type Model200Metrics

const _property_types_Model200Metrics = Dict{Symbol,String}(Symbol("metrics")=>"200MetricsMetrics", )
OpenAPI.property_type(::Type{ Model200Metrics }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_Model200Metrics[name]))}

function check_required(o::Model200Metrics)
    true
end

function OpenAPI.validate_property(::Type{ Model200Metrics }, name::Symbol, val)
end
