# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""response200SingleResult_result_services
The types of services

    Response200SingleResultResultServices(;
        acmecorp=nothing,
    )

    - acmecorp::Response200SingleResultResultServicesAcmecorp
"""
Base.@kwdef mutable struct Response200SingleResultResultServices <: OpenAPI.APIModel
    acmecorp = nothing # spec type: Union{ Nothing, Response200SingleResultResultServicesAcmecorp }

    function Response200SingleResultResultServices(acmecorp, )
        OpenAPI.validate_property(Response200SingleResultResultServices, Symbol("acmecorp"), acmecorp)
        return new(acmecorp, )
    end
end # type Response200SingleResultResultServices

const _property_types_Response200SingleResultResultServices = Dict{Symbol,String}(Symbol("acmecorp")=>"Response200SingleResultResultServicesAcmecorp", )
OpenAPI.property_type(::Type{ Response200SingleResultResultServices }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_Response200SingleResultResultServices[name]))}

function check_required(o::Response200SingleResultResultServices)
    true
end

function OpenAPI.validate_property(::Type{ Response200SingleResultResultServices }, name::Symbol, val)
end
