# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""_200Provenance_provenance

    200ProvenanceProvenance(;
        version=nothing,
        build_commit=nothing,
        build_timestamp=nothing,
        build_hostname=nothing,
        bundles=nothing,
    )

    - version::String : The version of this OPA instance
    - build_commit::String : The Git commit id of this OPA build.
    - build_timestamp::String : When this OPA instance was built (in [ISO8601 format](https://www.w3.org/TR/NOTE-datetime))
    - build_hostname::String : The hostname where this instance was built.
    - bundles::Dict{String, Any} : A set of key-value pairs describing each bundle activated on the server.
"""
Base.@kwdef mutable struct 200ProvenanceProvenance <: OpenAPI.APIModel
    version::Union{Nothing, String} = nothing
    build_commit::Union{Nothing, String} = nothing
    build_timestamp::Union{Nothing, String} = nothing
    build_hostname::Union{Nothing, String} = nothing
    bundles::Union{Nothing, Dict{String, Any}} = nothing

    function 200ProvenanceProvenance(version, build_commit, build_timestamp, build_hostname, bundles, )
        OpenAPI.validate_property(200ProvenanceProvenance, Symbol("version"), version)
        OpenAPI.validate_property(200ProvenanceProvenance, Symbol("build_commit"), build_commit)
        OpenAPI.validate_property(200ProvenanceProvenance, Symbol("build_timestamp"), build_timestamp)
        OpenAPI.validate_property(200ProvenanceProvenance, Symbol("build_hostname"), build_hostname)
        OpenAPI.validate_property(200ProvenanceProvenance, Symbol("bundles"), bundles)
        return new(version, build_commit, build_timestamp, build_hostname, bundles, )
    end
end # type 200ProvenanceProvenance

const _property_types_200ProvenanceProvenance = Dict{Symbol,String}(Symbol("version")=>"String", Symbol("build_commit")=>"String", Symbol("build_timestamp")=>"String", Symbol("build_hostname")=>"String", Symbol("bundles")=>"Dict{String, Any}", )
OpenAPI.property_type(::Type{ 200ProvenanceProvenance }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_200ProvenanceProvenance[name]))}

function check_required(o::200ProvenanceProvenance)
    true
end

function OpenAPI.validate_property(::Type{ 200ProvenanceProvenance }, name::Symbol, val)
end
