# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""response200Result

    Response200Result(;
        result=nothing,
    )

    - result::Vector{Response200ResultResultInner}
"""
Base.@kwdef mutable struct Response200Result <: OpenAPI.APIModel
    result::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{Response200ResultResultInner} }

    function Response200Result(result, )
        OpenAPI.validate_property(Response200Result, Symbol("result"), result)
        return new(result, )
    end
end # type Response200Result

const _property_types_Response200Result = Dict{Symbol,String}(Symbol("result")=>"Vector{Response200ResultResultInner}", )
OpenAPI.property_type(::Type{ Response200Result }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_Response200Result[name]))}

function check_required(o::Response200Result)
    true
end

function OpenAPI.validate_property(::Type{ Response200Result }, name::Symbol, val)
end
