# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""response200SingleResult_result_keys
Keys

    Response200SingleResultResultKeys(;
        var"global-key"=nothing,
    )

    - var"global-key"::Response200SingleResultResultKeysGlobalKey
"""
Base.@kwdef mutable struct Response200SingleResultResultKeys <: OpenAPI.APIModel
    var"global-key" = nothing # spec type: Union{ Nothing, Response200SingleResultResultKeysGlobalKey }

    function Response200SingleResultResultKeys(var"global-key", )
        OpenAPI.validate_property(Response200SingleResultResultKeys, Symbol("global-key"), var"global-key")
        return new(var"global-key", )
    end
end # type Response200SingleResultResultKeys

const _property_types_Response200SingleResultResultKeys = Dict{Symbol,String}(Symbol("global-key")=>"Response200SingleResultResultKeysGlobalKey", )
OpenAPI.property_type(::Type{ Response200SingleResultResultKeys }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_Response200SingleResultResultKeys[name]))}

function check_required(o::Response200SingleResultResultKeys)
    true
end

function OpenAPI.validate_property(::Type{ Response200SingleResultResultKeys }, name::Symbol, val)
end
