# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""response200Result_result_inner_ast_rules_inner_head_key
The type/value pairing for this rule&#39;s head

    Response200ResultResultInnerAstRulesInnerHeadKey(;
        type=nothing,
        value=nothing,
    )

    - type::String : The type of the head
    - value::String : The value of the head
"""
Base.@kwdef mutable struct Response200ResultResultInnerAstRulesInnerHeadKey <: OpenAPI.APIModel
    type::Union{Nothing, String} = nothing
    value::Union{Nothing, String} = nothing

    function Response200ResultResultInnerAstRulesInnerHeadKey(type, value, )
        OpenAPI.validate_property(Response200ResultResultInnerAstRulesInnerHeadKey, Symbol("type"), type)
        OpenAPI.validate_property(Response200ResultResultInnerAstRulesInnerHeadKey, Symbol("value"), value)
        return new(type, value, )
    end
end # type Response200ResultResultInnerAstRulesInnerHeadKey

const _property_types_Response200ResultResultInnerAstRulesInnerHeadKey = Dict{Symbol,String}(Symbol("type")=>"String", Symbol("value")=>"String", )
OpenAPI.property_type(::Type{ Response200ResultResultInnerAstRulesInnerHeadKey }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_Response200ResultResultInnerAstRulesInnerHeadKey[name]))}

function check_required(o::Response200ResultResultInnerAstRulesInnerHeadKey)
    true
end

function OpenAPI.validate_property(::Type{ Response200ResultResultInnerAstRulesInnerHeadKey }, name::Symbol, val)
end
