# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""response200SingleResult_result_labels
Labels

    Response200SingleResultResultLabels(;
        id=nothing,
        version=nothing,
    )

    - id::String : Label ID
    - version::String : Version
"""
Base.@kwdef mutable struct Response200SingleResultResultLabels <: OpenAPI.APIModel
    id::Union{Nothing, String} = nothing
    version::Union{Nothing, String} = nothing

    function Response200SingleResultResultLabels(id, version, )
        OpenAPI.validate_property(Response200SingleResultResultLabels, Symbol("id"), id)
        OpenAPI.validate_property(Response200SingleResultResultLabels, Symbol("version"), version)
        return new(id, version, )
    end
end # type Response200SingleResultResultLabels

const _property_types_Response200SingleResultResultLabels = Dict{Symbol,String}(Symbol("id")=>"String", Symbol("version")=>"String", )
OpenAPI.property_type(::Type{ Response200SingleResultResultLabels }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_Response200SingleResultResultLabels[name]))}

function check_required(o::Response200SingleResultResultLabels)
    true
end

function OpenAPI.validate_property(::Type{ Response200SingleResultResultLabels }, name::Symbol, val)
    if name === Symbol("id")
        OpenAPI.validate_param(name, "Response200SingleResultResultLabels", :minLength, val, 1)
    end
    if name === Symbol("version")
        OpenAPI.validate_param(name, "Response200SingleResultResultLabels", :minLength, val, 1)
    end
end
