# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""response200SingleResult_result_bundles
Bundles

    Response200SingleResultResultBundles(;
        authz=nothing,
    )

    - authz::Response200SingleResultResultBundlesAuthz
"""
Base.@kwdef mutable struct Response200SingleResultResultBundles <: OpenAPI.APIModel
    authz = nothing # spec type: Union{ Nothing, Response200SingleResultResultBundlesAuthz }

    function Response200SingleResultResultBundles(authz, )
        OpenAPI.validate_property(Response200SingleResultResultBundles, Symbol("authz"), authz)
        return new(authz, )
    end
end # type Response200SingleResultResultBundles

const _property_types_Response200SingleResultResultBundles = Dict{Symbol,String}(Symbol("authz")=>"Response200SingleResultResultBundlesAuthz", )
OpenAPI.property_type(::Type{ Response200SingleResultResultBundles }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_Response200SingleResultResultBundles[name]))}

function check_required(o::Response200SingleResultResultBundles)
    true
end

function OpenAPI.validate_property(::Type{ Response200SingleResultResultBundles }, name::Symbol, val)
end
