# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""response200Explanations_explanation_inner_locals_inner_key

    Response200ExplanationsExplanationInnerLocalsInnerKey(;
        type=nothing,
        value=nothing,
    )

    - type::String
    - value::String
"""
Base.@kwdef mutable struct Response200ExplanationsExplanationInnerLocalsInnerKey <: OpenAPI.APIModel
    type::Union{Nothing, String} = nothing
    value::Union{Nothing, String} = nothing

    function Response200ExplanationsExplanationInnerLocalsInnerKey(type, value, )
        OpenAPI.validate_property(Response200ExplanationsExplanationInnerLocalsInnerKey, Symbol("type"), type)
        OpenAPI.validate_property(Response200ExplanationsExplanationInnerLocalsInnerKey, Symbol("value"), value)
        return new(type, value, )
    end
end # type Response200ExplanationsExplanationInnerLocalsInnerKey

const _property_types_Response200ExplanationsExplanationInnerLocalsInnerKey = Dict{Symbol,String}(Symbol("type")=>"String", Symbol("value")=>"String", )
OpenAPI.property_type(::Type{ Response200ExplanationsExplanationInnerLocalsInnerKey }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_Response200ExplanationsExplanationInnerLocalsInnerKey[name]))}

function check_required(o::Response200ExplanationsExplanationInnerLocalsInnerKey)
    true
end

function OpenAPI.validate_property(::Type{ Response200ExplanationsExplanationInnerLocalsInnerKey }, name::Symbol, val)
end
