# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""response200SingleResult

    Response200SingleResult(;
        result=nothing,
    )

    - result::Response200SingleResultResult
"""
Base.@kwdef mutable struct Response200SingleResult <: OpenAPI.APIModel
    result = nothing # spec type: Union{ Nothing, Response200SingleResultResult }

    function Response200SingleResult(result, )
        OpenAPI.validate_property(Response200SingleResult, Symbol("result"), result)
        return new(result, )
    end
end # type Response200SingleResult

const _property_types_Response200SingleResult = Dict{Symbol,String}(Symbol("result")=>"Response200SingleResultResult", )
OpenAPI.property_type(::Type{ Response200SingleResult }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_Response200SingleResult[name]))}

function check_required(o::Response200SingleResult)
    true
end

function OpenAPI.validate_property(::Type{ Response200SingleResult }, name::Symbol, val)
end
