# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""response200Explanations

    Response200Explanations(;
        explanation=nothing,
    )

    - explanation::Vector{Response200ExplanationsExplanationInner}
"""
Base.@kwdef mutable struct Response200Explanations <: OpenAPI.APIModel
    explanation::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{Response200ExplanationsExplanationInner} }

    function Response200Explanations(explanation, )
        OpenAPI.validate_property(Response200Explanations, Symbol("explanation"), explanation)
        return new(explanation, )
    end
end # type Response200Explanations

const _property_types_Response200Explanations = Dict{Symbol,String}(Symbol("explanation")=>"Vector{Response200ExplanationsExplanationInner}", )
OpenAPI.property_type(::Type{ Response200Explanations }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_Response200Explanations[name]))}

function check_required(o::Response200Explanations)
    true
end

function OpenAPI.validate_property(::Type{ Response200Explanations }, name::Symbol, val)
end
