# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""response200Result_result_inner_ast_package

    Response200ResultResultInnerAstPackage(;
        path=nothing,
    )

    - path::Vector{Response200ResultResultInnerAstPackagePathInner} : The path to the package
"""
Base.@kwdef mutable struct Response200ResultResultInnerAstPackage <: OpenAPI.APIModel
    path::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{Response200ResultResultInnerAstPackagePathInner} }

    function Response200ResultResultInnerAstPackage(path, )
        OpenAPI.validate_property(Response200ResultResultInnerAstPackage, Symbol("path"), path)
        return new(path, )
    end
end # type Response200ResultResultInnerAstPackage

const _property_types_Response200ResultResultInnerAstPackage = Dict{Symbol,String}(Symbol("path")=>"Vector{Response200ResultResultInnerAstPackagePathInner}", )
OpenAPI.property_type(::Type{ Response200ResultResultInnerAstPackage }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_Response200ResultResultInnerAstPackage[name]))}

function check_required(o::Response200ResultResultInnerAstPackage)
    true
end

function OpenAPI.validate_property(::Type{ Response200ResultResultInnerAstPackage }, name::Symbol, val)
end
