# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""response400

    Response400(;
        code=nothing,
        message=nothing,
        errors=nothing,
    )

    - code::String : The error code name
    - message::String : The description of the error
    - errors::Vector{Response400ErrorsInner} : Errors that may have been generated during the parse, compile, or installation of a policy module
"""
Base.@kwdef mutable struct Response400 <: OpenAPI.APIModel
    code::Union{Nothing, String} = nothing
    message::Union{Nothing, String} = nothing
    errors::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{Response400ErrorsInner} }

    function Response400(code, message, errors, )
        OpenAPI.validate_property(Response400, Symbol("code"), code)
        OpenAPI.validate_property(Response400, Symbol("message"), message)
        OpenAPI.validate_property(Response400, Symbol("errors"), errors)
        return new(code, message, errors, )
    end
end # type Response400

const _property_types_Response400 = Dict{Symbol,String}(Symbol("code")=>"String", Symbol("message")=>"String", Symbol("errors")=>"Vector{Response400ErrorsInner}", )
OpenAPI.property_type(::Type{ Response400 }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_Response400[name]))}

function check_required(o::Response400)
    o.code === nothing && (return false)
    o.message === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ Response400 }, name::Symbol, val)
    if name === Symbol("code")
        OpenAPI.validate_param(name, "Response400", :minLength, val, 1)
    end
    if name === Symbol("message")
        OpenAPI.validate_param(name, "Response400", :minLength, val, 1)
    end
    if name === Symbol("errors")
        OpenAPI.validate_param(name, "Response400", :uniqueItems, val, true)
    end
end
